# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stimdx.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'stimdx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstimdx.proto\x12\x06stimdx\"?\n\tStimBlock\x12\x19\n\x11stim_circuit_text\x18\x01 \x01(\t\x12\x17\n\x0f\x63\x61pture_as_last\x18\x02 \x01(\x08\"\"\n\x11LastMeasCondition\x12\r\n\x05index\x18\x01 \x01(\x05\"&\n\x13MeasParityCondition\x12\x0f\n\x07indices\x18\x01 \x03(\x05\"|\n\tCondition\x12.\n\tlast_meas\x18\x01 \x01(\x0b\x32\x19.stimdx.LastMeasConditionH\x00\x12\x32\n\x0bmeas_parity\x18\x02 \x01(\x0b\x32\x1b.stimdx.MeasParityConditionH\x00\x42\x0b\n\tcond_type\"M\n\x06IfNode\x12$\n\tcondition\x18\x01 \x01(\x0b\x32\x11.stimdx.Condition\x12\x1d\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x0f.stimdx.Circuit\"b\n\tWhileNode\x12$\n\tcondition\x18\x01 \x01(\x0b\x32\x11.stimdx.Condition\x12\x1d\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x0f.stimdx.Circuit\x12\x10\n\x08max_iter\x18\x03 \x01(\x05\"d\n\x0b\x44oWhileNode\x12$\n\tcondition\x18\x01 \x01(\x0b\x32\x11.stimdx.Condition\x12\x1d\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x0f.stimdx.Circuit\x12\x10\n\x08max_iter\x18\x03 \x01(\x05\"\xb6\x01\n\x04Node\x12\'\n\nstim_block\x18\x01 \x01(\x0b\x32\x11.stimdx.StimBlockH\x00\x12!\n\x07if_node\x18\x02 \x01(\x0b\x32\x0e.stimdx.IfNodeH\x00\x12\'\n\nwhile_node\x18\x03 \x01(\x0b\x32\x11.stimdx.WhileNodeH\x00\x12,\n\rdo_while_node\x18\x04 \x01(\x0b\x32\x13.stimdx.DoWhileNodeH\x00\x42\x0b\n\tnode_type\"&\n\x07\x43ircuit\x12\x1b\n\x05nodes\x18\x01 \x03(\x0b\x32\x0c.stimdx.Node\"\\\n\rSampleRequest\x12 \n\x07\x63ircuit\x18\x01 \x01(\x0b\x32\x0f.stimdx.Circuit\x12\r\n\x05shots\x18\x02 \x01(\x05\x12\x11\n\x04seed\x18\x03 \x01(\x03H\x00\x88\x01\x01\x42\x07\n\x05_seed\")\n\x11MeasurementRecord\x12\x14\n\x0cmeasurements\x18\x01 \x03(\x08\"<\n\x0eSampleResponse\x12*\n\x07records\x18\x01 \x03(\x0b\x32\x19.stimdx.MeasurementRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stimdx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STIMBLOCK']._serialized_start=24
  _globals['_STIMBLOCK']._serialized_end=87
  _globals['_LASTMEASCONDITION']._serialized_start=89
  _globals['_LASTMEASCONDITION']._serialized_end=123
  _globals['_MEASPARITYCONDITION']._serialized_start=125
  _globals['_MEASPARITYCONDITION']._serialized_end=163
  _globals['_CONDITION']._serialized_start=165
  _globals['_CONDITION']._serialized_end=289
  _globals['_IFNODE']._serialized_start=291
  _globals['_IFNODE']._serialized_end=368
  _globals['_WHILENODE']._serialized_start=370
  _globals['_WHILENODE']._serialized_end=468
  _globals['_DOWHILENODE']._serialized_start=470
  _globals['_DOWHILENODE']._serialized_end=570
  _globals['_NODE']._serialized_start=573
  _globals['_NODE']._serialized_end=755
  _globals['_CIRCUIT']._serialized_start=757
  _globals['_CIRCUIT']._serialized_end=795
  _globals['_SAMPLEREQUEST']._serialized_start=797
  _globals['_SAMPLEREQUEST']._serialized_end=889
  _globals['_MEASUREMENTRECORD']._serialized_start=891
  _globals['_MEASUREMENTRECORD']._serialized_end=932
  _globals['_SAMPLERESPONSE']._serialized_start=934
  _globals['_SAMPLERESPONSE']._serialized_end=994
# @@protoc_insertion_point(module_scope)
